[2017-07-31 23:20:58] console.ERROR: Error thrown while running command "'debug:rout'". Message: "Call to a member function get() on null" {"error":"[object] (Error(code: 0): Call to a member function get() on null at /mnt/e/var/www/autocrm/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php:50)","command":"'debug:rout'","message":"Call to a member function get() on null"} []
[2017-07-31 23:21:02] console.ERROR: Command "'debug:rout'" exited with code "1" {"command":"'debug:rout'","code":1} []
[2017-07-31 23:21:06] php.CRITICAL: Call to a member function get() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function get() on null at /mnt/e/var/www/autocrm/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php:50)"} []
[2017-07-31 23:22:57] console.ERROR: Error thrown while running command "'debug:rout'". Message: "Call to a member function get() on null" {"error":"[object] (Error(code: 0): Call to a member function get() on null at /mnt/e/var/www/autocrm/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php:50)","command":"'debug:rout'","message":"Call to a member function get() on null"} []
[2017-07-31 23:23:00] console.ERROR: Command "'debug:rout'" exited with code "1" {"command":"'debug:rout'","code":1} []
[2017-07-31 23:23:04] php.CRITICAL: Call to a member function get() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function get() on null at /mnt/e/var/www/autocrm/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php:50)"} []
[2017-07-31 23:27:15] console.ERROR: Error thrown while running command "'debug:rout'". Message: "Call to a member function get() on null" {"error":"[object] (Error(code: 0): Call to a member function get() on null at /mnt/e/var/www/autocrm/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php:50)","command":"'debug:rout'","message":"Call to a member function get() on null"} []
[2017-07-31 23:27:18] console.ERROR: Command "'debug:rout'" exited with code "1" {"command":"'debug:rout'","code":1} []
[2017-07-31 23:27:22] php.CRITICAL: Call to a member function get() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function get() on null at /mnt/e/var/www/autocrm/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php:50)"} []
[2017-07-31 23:28:14] console.ERROR: Error thrown while running command "'debug:rout'". Message: "Call to a member function get() on null" {"error":"[object] (Error(code: 0): Call to a member function get() on null at /mnt/e/var/www/autocrm/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php:50)","command":"'debug:rout'","message":"Call to a member function get() on null"} []
[2017-07-31 23:28:17] console.ERROR: Command "'debug:rout'" exited with code "1" {"command":"'debug:rout'","code":1} []
[2017-07-31 23:28:21] php.CRITICAL: Call to a member function get() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function get() on null at /mnt/e/var/www/autocrm/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php:50)"} []
[2017-07-31 23:29:08] console.ERROR: Error thrown while running command "'debug:rout'". Message: "Call to a member function get() on null" {"error":"[object] (Error(code: 0): Call to a member function get() on null at /mnt/e/var/www/autocrm/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php:50)","command":"'debug:rout'","message":"Call to a member function get() on null"} []
[2017-07-31 23:29:11] console.ERROR: Command "'debug:rout'" exited with code "1" {"command":"'debug:rout'","code":1} []
[2017-07-31 23:29:15] php.CRITICAL: Call to a member function get() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function get() on null at /mnt/e/var/www/autocrm/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php:50)"} []
[2017-07-31 23:31:05] console.ERROR: Error thrown while running command "'debug:rout'". Message: "Call to a member function get() on null" {"error":"[object] (Error(code: 0): Call to a member function get() on null at /mnt/e/var/www/autocrm/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php:50)","command":"'debug:rout'","message":"Call to a member function get() on null"} []
[2017-07-31 23:31:08] console.ERROR: Command "'debug:rout'" exited with code "1" {"command":"'debug:rout'","code":1} []
[2017-07-31 23:31:12] php.CRITICAL: Call to a member function get() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function get() on null at /mnt/e/var/www/autocrm/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php:50)"} []
[2017-07-31 23:34:24] console.ERROR: Error thrown while running command "'debug:rout'". Message: "Call to a member function get() on null" {"error":"[object] (Error(code: 0): Call to a member function get() on null at /mnt/e/var/www/autocrm/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php:50)","command":"'debug:rout'","message":"Call to a member function get() on null"} []
[2017-07-31 23:34:27] console.ERROR: Command "'debug:rout'" exited with code "1" {"command":"'debug:rout'","code":1} []
[2017-07-31 23:34:31] php.CRITICAL: Call to a member function get() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function get() on null at /mnt/e/var/www/autocrm/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php:50)"} []
[2017-07-31 23:41:07] console.ERROR: Error thrown while running command "'debug:rout'". Message: "Call to a member function get() on null" {"error":"[object] (Error(code: 0): Call to a member function get() on null at /mnt/e/var/www/autocrm/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php:50)","command":"'debug:rout'","message":"Call to a member function get() on null"} []
[2017-07-31 23:41:10] console.ERROR: Command "'debug:rout'" exited with code "1" {"command":"'debug:rout'","code":1} []
[2017-07-31 23:41:14] php.CRITICAL: Call to a member function get() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function get() on null at /mnt/e/var/www/autocrm/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php:50)"} []
